"""empty message

Revision ID: 193ed17e8ce2
Revises: 
Create Date: 2025-11-17 15:20:04.972135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '193ed17e8ce2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.alter_column('empresa_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
