"""empty message

Revision ID: 1b2362e9aefb
Revises: 5a24fddef44d
Create Date: 2025-07-16 10:18:55.345553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b2362e9aefb'
down_revision = '5a24fddef44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj_cpf', sa.String(length=15), nullable=True))
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', mysql.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('cnpj_cpf')

    # ### end Alembic commands ###
