"""empty message

Revision ID: 223f21834b29
Revises: 51d7ebdc5a99
Create Date: 2025-12-30 09:27:45.228308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223f21834b29'
down_revision = '51d7ebdc5a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.alter_column('atualizacao',
               existing_type=sa.DATE(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.alter_column('atualizacao',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
