"""empty message

Revision ID: 238d468bfa2c
Revises: f66de3d56de9
Create Date: 2025-10-03 15:39:24.397296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '238d468bfa2c'
down_revision = 'f66de3d56de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index('tax_id')

    op.drop_table('empresa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('tax_id', mysql.VARCHAR(length=18), nullable=True),
    sa.Column('opening_date', sa.DATE(), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('trade_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('main_activity_code', mysql.JSON(), nullable=True),
    sa.Column('secondary_activity_codes', mysql.JSON(), nullable=True),
    sa.Column('legal_activity_codes', mysql.JSON(), nullable=True),
    sa.Column('street', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complement', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('zip_code', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('district', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_index('tax_id', ['tax_id'], unique=True)

    # ### end Alembic commands ###
