"""empty message

Revision ID: 29e8d839e077
Revises: 
Create Date: 2025-10-10 11:01:14.885922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29e8d839e077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])
        batch_op.drop_column('empresa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
