"""empty message

Revision ID: 3da0a95b0148
Revises: f820274d813e
Create Date: 2025-11-27 14:22:46.349981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da0a95b0148'
down_revision = 'f820274d813e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
