"""initial migration

Revision ID: 4544ee4da134
Revises: 
Create Date: 2025-04-23 12:12:36.833611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4544ee4da134'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_constraint('contratos_ibfk_3', type_='foreignkey')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('contratos_ibfk_3', 'clientes', ['cliente_id'], ['id'])

    # ### end Alembic commands ###
