"""empty message

Revision ID: 51d7ebdc5a99
Revises: d408ca0f68a4
Create Date: 2025-12-29 10:38:42.771630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51d7ebdc5a99'
down_revision = 'd408ca0f68a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('ativo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ativo', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
