"""empty message

Revision ID: 7551bf39d330
Revises: 193ed17e8ce2
Create Date: 2025-11-26 10:27:09.687813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7551bf39d330'
down_revision = '193ed17e8ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente_contrato', schema=None) as batch_op:
        batch_op.drop_constraint('cliente_contrato_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('cliente_contrato_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contratos', ['contrato_id'], ['id'])
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.String(length=100), nullable=True))
        batch_op.alter_column('motivo_estado',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.alter_column('motivo_estado',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('observacao')

    with op.batch_alter_table('cliente_contrato', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cliente_contrato_ibfk_1', 'clientes', ['cliente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('cliente_contrato_ibfk_2', 'contratos', ['contrato_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
