"""initial migration

Revision ID: 75d90ab14ee1
Revises: 4544ee4da134
Create Date: 2025-04-25 11:25:15.636226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d90ab14ee1'
down_revision = '4544ee4da134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_contrato', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('numero_contrato')

    # ### end Alembic commands ###
