"""empty message

Revision ID: 79179acfc440
Revises: 396f20dcfd97
Create Date: 2025-07-14 16:31:02.433676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79179acfc440'
down_revision = '396f20dcfd97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd_produto', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_column('qtd_produto')

    # ### end Alembic commands ###
