"""empty message

Revision ID: 800f36018be0
Revises: 9a166235f1d0
Create Date: 2025-07-15 09:47:40.689063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800f36018be0'
down_revision = '9a166235f1d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_base_produto', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_column('valor_base_produto')

    # ### end Alembic commands ###
