"""empty message

Revision ID: 8ea28927934b
Revises: 9bbbfe69b1ae
Create Date: 2025-10-31 12:26:35.764375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ea28927934b'
down_revision = '9bbbfe69b1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj_cpf', sa.String(length=18), nullable=True))
        batch_op.drop_column('cnpj')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj', mysql.VARCHAR(length=18), nullable=True))
        batch_op.drop_column('cnpj_cpf')

    # ### end Alembic commands ###
