"""empty message

Revision ID: 9a166235f1d0
Revises: fb3209400326
Create Date: 2025-07-14 16:50:54.765037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a166235f1d0'
down_revision = 'fb3209400326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc_nf_licenca', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_column('desc_nf_licenca')

    # ### end Alembic commands ###
