"""empty message

Revision ID: 9bbbfe69b1ae
Revises: 29e8d839e077
Create Date: 2025-10-10 11:11:15.173455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bbbfe69b1ae'
down_revision = '29e8d839e077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.alter_column('cnpj_cpf',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.alter_column('cnpj_cpf',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###
