"""empty message

Revision ID: cb37de35c7d1
Revises: 3da0a95b0148
Create Date: 2025-12-15 11:21:37.497089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb37de35c7d1'
down_revision = '3da0a95b0148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atualizacao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.drop_column('atualizacao')

    # ### end Alembic commands ###
