"""empty message

Revision ID: d3a7a4f43ee2
Revises: 8ea28927934b
Create Date: 2025-11-07 14:21:26.641997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd3a7a4f43ee2'
down_revision = '8ea28927934b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_column('responsavel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsavel', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
