"""empty message

Revision ID: d408ca0f68a4
Revises: cb37de35c7d1
Create Date: 2025-12-18 10:17:45.923517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd408ca0f68a4'
down_revision = 'cb37de35c7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.alter_column('cliente_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
