"""empty message

Revision ID: df4bd1f78561
Revises: 1b2362e9aefb
Create Date: 2025-10-03 15:34:50.675728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4bd1f78561'
down_revision = '1b2362e9aefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_desc_juridica', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')
        batch_op.drop_column('uf')
        batch_op.drop_column('municipio')
        batch_op.drop_column('bairro')
        batch_op.drop_column('cep')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cod_desc_juridica')

    # ### end Alembic commands ###
