"""empty message

Revision ID: f66de3d56de9
Revises: df4bd1f78561
Create Date: 2025-10-03 15:38:36.812403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f66de3d56de9'
down_revision = 'df4bd1f78561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_id', sa.String(length=18), nullable=True))
        batch_op.add_column(sa.Column('opening_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('trade_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('main_activity_code', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('secondary_activity_codes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('legal_activity_codes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('complement', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))
        batch_op.drop_index('cnpj')
        batch_op.create_unique_constraint(None, ['tax_id'])
        batch_op.drop_column('nome_empresa')
        batch_op.drop_column('cnpj')
        batch_op.drop_column('cod_desc_principal')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cod_desc_juridica')
        batch_op.drop_column('municipio')
        batch_op.drop_column('complemento')
        batch_op.drop_column('telefone')
        batch_op.drop_column('nome_fantasia')
        batch_op.drop_column('bairro')
        batch_op.drop_column('data_abertura')
        batch_op.drop_column('numero')
        batch_op.drop_column('uf')
        batch_op.drop_column('cep')
        batch_op.drop_column('cod_desc_secundaria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_desc_secundaria', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cep', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uf', mysql.VARCHAR(length=2), nullable=True))
        batch_op.add_column(sa.Column('numero', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_abertura', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('bairro', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('nome_fantasia', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefone', mysql.VARCHAR(length=15), nullable=True))
        batch_op.add_column(sa.Column('complemento', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('municipio', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('cod_desc_juridica', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('logradouro', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('cod_desc_principal', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cnpj', mysql.VARCHAR(length=18), nullable=True))
        batch_op.add_column(sa.Column('nome_empresa', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('cnpj', ['cnpj'], unique=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('district')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('complement')
        batch_op.drop_column('number')
        batch_op.drop_column('street')
        batch_op.drop_column('legal_activity_codes')
        batch_op.drop_column('secondary_activity_codes')
        batch_op.drop_column('main_activity_code')
        batch_op.drop_column('trade_name')
        batch_op.drop_column('company_name')
        batch_op.drop_column('opening_date')
        batch_op.drop_column('tax_id')

    # ### end Alembic commands ###
