"""empty message

Revision ID: f820274d813e
Revises: 7551bf39d330
Create Date: 2025-11-26 13:34:44.046942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f820274d813e'
down_revision = '7551bf39d330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cliente_plano')
    op.drop_table('cliente_produto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_produto',
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='cliente_produto_ibfk_1'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name='cliente_produto_ibfk_2'),
    sa.PrimaryKeyConstraint('cliente_id', 'produto_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cliente_plano',
    sa.Column('cliente_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plano_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='cliente_plano_ibfk_1'),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], name='cliente_plano_ibfk_2'),
    sa.PrimaryKeyConstraint('cliente_id', 'plano_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
