"""empty message

Revision ID: fb3209400326
Revises: 79179acfc440
Create Date: 2025-07-14 16:49:10.696349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb3209400326'
down_revision = '79179acfc440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_column('desc_nf_monitoramento')
        batch_op.drop_column('cod_servico_sp_suporte')
        batch_op.drop_column('cod_servico_barueri_suporte')
        batch_op.drop_column('desc_boleto_suporte')
        batch_op.drop_column('desc_nf_suporte')
        batch_op.drop_column('aliquota_sp_gerenciamento')
        batch_op.drop_column('aliquota_barueri_suporte')
        batch_op.drop_column('aliquota_sp_suporte')
        batch_op.drop_column('cod_servico_barueri_manutencao')
        batch_op.drop_column('cod_servico_barueri_gerenciamento')
        batch_op.drop_column('desc_nf_licenca')
        batch_op.drop_column('desc_nf_hospedagem')
        batch_op.drop_column('cod_servico_barueri_licenca')
        batch_op.drop_column('desc_nf_gerenciamento')
        batch_op.drop_column('aliquota_barueri_monitoramento')
        batch_op.drop_column('desc_boleto_gerenciamento')
        batch_op.drop_column('cod_servico_sp_monitoramento')
        batch_op.drop_column('aliquota_barueri_licenca')
        batch_op.drop_column('desc_boleto_hospedagem')
        batch_op.drop_column('aliquota_barueri_hospedagem')
        batch_op.drop_column('cod_servico_sp_hospedagem')
        batch_op.drop_column('desc_nf_manutencao')
        batch_op.drop_column('aliquota_sp_monitoramento')
        batch_op.drop_column('aliquota_sp_hospedagem')
        batch_op.drop_column('aliquota_sp_manutencao')
        batch_op.drop_column('cod_servico_barueri_hospedagem')
        batch_op.drop_column('desc_boleto_monitoramento')
        batch_op.drop_column('aliquota_barueri_gerenciamento')
        batch_op.drop_column('cod_servico_sp_manutencao')
        batch_op.drop_column('aliquota_barueri_manutencao')
        batch_op.drop_column('desc_boleto_manutencao')
        batch_op.drop_column('cod_servico_barueri_monitoramento')
        batch_op.drop_column('cod_servico_sp_gerenciamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_servico_sp_gerenciamento', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_barueri_monitoramento', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('desc_boleto_manutencao', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('aliquota_barueri_manutencao', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_sp_manutencao', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('aliquota_barueri_gerenciamento', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('desc_boleto_monitoramento', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_barueri_hospedagem', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('aliquota_sp_manutencao', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('aliquota_sp_hospedagem', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('aliquota_sp_monitoramento', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('desc_nf_manutencao', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_sp_hospedagem', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('aliquota_barueri_hospedagem', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('desc_boleto_hospedagem', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('aliquota_barueri_licenca', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_sp_monitoramento', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('desc_boleto_gerenciamento', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('aliquota_barueri_monitoramento', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('desc_nf_gerenciamento', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_barueri_licenca', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('desc_nf_hospedagem', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('desc_nf_licenca', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_barueri_gerenciamento', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_barueri_manutencao', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('aliquota_sp_suporte', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('aliquota_barueri_suporte', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('aliquota_sp_gerenciamento', mysql.DECIMAL(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('desc_nf_suporte', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('desc_boleto_suporte', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_barueri_suporte', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('cod_servico_sp_suporte', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('desc_nf_monitoramento', mysql.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
